apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
     metadata:
        labels:
           app: mysql
     spec:
        containers:
        - name: con1
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef: 
                   name: mypass
                   key: password 
          - name: MYSQL_DATABASE
            value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306

