apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
     metadata:
        labels:
           app: wordpress
     spec:
        containers:
        - name: con1
          image: wordpress:latest
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
               name: wp 
          
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123

