apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
     metadata:
        labels:
           app: wordpress
     spec:
        containers:
        - name: con1
          image: wordpress:latest
          ports:
          - containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
               configMapKeyRef:
                  name: wp
                  key: WORDPRESS_DB_HOST
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: test123
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_TABLE_PREFIX
            value: wp_ 
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123

